### ISSUE TITLE
Can BeauRoutine Sequences, Combine works with DOTween

### ISSUE THREAD

**Issue by takaaptech** [FilamentGames/BeauRoutine#2] opened 2018-10-09 08:24 UTC
Hi!
I like this very much and using BeauToutine, I can construct code and logic much easier and clear.
For now, I have some old projects that heavy base on DOTween. So can I have something like adapter/bridge class or function to using DOTween with  BeauRoutine?
I try some method like this
```
IEnumerator TweentoBeauRoutine(Tween tween)
	{	
		yield return tween.WaitForCompletion();
	}
```
And then using Yield or Then like this
```
var routine1 = BeauRoutine.Sequence.Create(transform.GetComponent<SpriteRenderer>().FadeTo(1f,1f)).Wait(1)
				.Then(transform.ScaleTo(0.65f,0.2f))
				.Then(transform.ScaleTo( 0.55f,0.1f))
				.Then(transform.ScaleTo(0.65f,0.05f))
				//.Yield(TweentoBeauRoutine(this.Scale(1f,2.0f)))
				.Then(() =>
				{
					print("OK here");
				})
			;
```
But DoTween is always executed before Routine.Start(this, routine);
Tween in BeauRoutine is awesome too but it takes time to convert all my DOTween functions to BeauRoutine so I am looking for way to wrapper it.
Thanks!

**Comment by BeauchesneFilament** [comment] 2018-10-18 19:33
Thanks for your patience. There are two basic approaches I found to this problem.

The first involves minimal integration with BeauRoutine features and looks something like this:
```csharp /// <summary>
/// Lightweight wrapper for a DOTween.
/// This will simply run the tween once this step is invoked and wait for it to complete.
/// It ignores BeauRoutine timescale, pausing, stopping, etc.
/// </summary>
static public IEnumerator WrapLightweight(DG.Tweening.Tween inTween)
{
    inTween.Pause();
    return LightweightWrapper(inTween);
}

static private IEnumerator LightweightWrapper(DG.Tweening.Tween inTween)
{
    inTween.Play();
    yield return inTween.WaitForCompletion();
}
```
This pauses the tween immediately and returns a coroutine that will play the tween and wait for it to complete. Doesn't integrate well with BeauRoutine features like pausing, resuming, timescale, and the like, since this still uses DOTween's update loop.

A second approach is more complex, and involves using the tween's Goto method inside of a custom IEnumerator class.

```csharp /// <summary>
/// Wrapper for a DOTween.
/// This is integrated into BeauRoutine's runtime,
/// including timescale, pausing, stopping, etc.
/// </summary>
static public IEnumerator Wrap(DG.Tweening.Tween inTween)
{
    return new DOTweenRunner(inTween);
}

private class DOTweenRunner : IEnumerator, IDisposable
{
    private enum Stage
    {
        NeedsInitialize,
        Running,
        Done
    }

    private DG.Tweening.Tween m_Tween;
    private float m_CurrentTime;
    private Stage m_Stage;

    public DOTweenRunner(DG.Tweening.Tween inTween)
    {
        m_Tween = inTween;
        inTween.Pause();
        m_Stage = Stage.NeedsInitialize;
        m_CurrentTime = 0;
    }

    public void Dispose()
    {
        if (m_Tween != null)
        {
            if (m_Tween.IsActive())
            {
                m_Tween.Kill(false);
                m_Tween = null;
            }
        }
    }

    public bool MoveNext()
    {
        if (m_Stage == Stage.NeedsInitialize)
        {
            m_CurrentTime = m_Tween.fullPosition;
            if (m_CurrentTime <= 0)
            {
                m_CurrentTime = -m_Tween.Delay();
            }
            m_Stage = Stage.Running;
        }

        if (m_Stage == Stage.Running)
        {
            float dt = Routine.DeltaTime * DOTween.timeScale * m_Tween.timeScale;
            m_CurrentTime += dt;
            if (m_CurrentTime >= 0)
            {
                m_Tween.Goto(m_CurrentTime);
                if (m_Tween.IsComplete())
                {
                    m_Stage = Stage.Done;
                }
            }
        }

        return m_Stage != Stage.Done;
    }

    public object Current
    {
        get { return null; }
    }

    public void Reset()
    {
        throw new InvalidOperationException();
    }

    public override string ToString()
    {
        if (m_Tween != null)
        {
            return "DOTweenWrapper: " + m_Tween.ToString();
        }
        return "DOTweenWrapper: [null]";
    }
}
```
This is the superior approach if you're looking to make use of pausing, resuming, and timescaling for your BeauRoutines.

I combined both of these approaches into a wrapper class [here](https://gist.github.com/BeauchesneFilament/c7dcab5a50298a16cba332b33ea6a6db). Hopefully you find this useful!

**Comment by BeauchesneFilament** [comment] 2018-10-25 17:07
Right, that's the intended behavior. `Wait()` waits for the given routine to finish executing. It doesn't pause until the sequence reaches that point, and that wasn't really a use case that sequence was designed for.

If you just need that behavior, you could write something very similar to the lightweight wrapper I posted earlier, substituting a `Routine` in place of the `DG.Tweening.Tween` and yielding a `.Wait()` instead of a `.WaitForCompletion()`.

Alternately, you could use a `.Yield()` instead of a `.Then()`, with something like `seq_routine.Yield( () => return moveAnimation.Replace(this, SomeMovementAnim(someArg)) )`. That will effectively start the movement animation at that particular point in the sequence, assign it to the appropriate handle, and wait for it to complete.

Let me know if this covers your use case.

**Closed as completed** 2018-10-26 03:26 UTC
